name: Check for formatting

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use node js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Fomat
        run: npm run format
